
const SUPABASE_URL = 'https://xiawqzxqoimgdfjmgyqy.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_RfHhNxAeZRag1kKKMduqvw_JzX6HJux';

function fatalPanel(message) {
  const el = document.querySelector('#admin-app');
  if (el) {
    el.innerHTML = `<div style="min-height:100vh;display:grid;place-items:center;padding:24px;background:#f3f6fa;font-family:Arial,sans-serif">
      <div style="max-width:620px;background:#fff;border:1px solid #e3e8f0;border-radius:18px;padding:24px;box-shadow:0 20px 55px rgba(20,30,70,.12)">
        <h2 style="margin-top:0;color:#2c3091">Não foi possível carregar o painel</h2>
        <p style="color:#566070;line-height:1.55">${String(message || 'Erro desconhecido')}</p>
        <p style="font-size:13px;color:#7b8494">Atualize a página. Se a mensagem continuar aparecendo, envie uma foto desta tela.</p>
      </div>
    </div>`;
  }
}

if (!window.supabase || typeof window.supabase.createClient !== 'function') {
  fatalPanel('A biblioteca de conexão com o Supabase não foi carregada.');
  throw new Error('Supabase JS não carregou.');
}

const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});


const app=document.querySelector('#admin-app');
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugify=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const fmt=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(v+(String(v).length===10?'T12:00:00':''))):'—';
const state={session:null,view:'dashboard',edit:null,msg:'',err:'',counts:{},settings:null,rows:[]};
const documentCategories=[['institucional','Institucional / Estatuto'],['emendas','Parcerias e Termos de Fomento'],['planos','Planos de Trabalho'],['contas','Prestação de Contas'],['relatorios','Relatórios de Atividades'],['balancos','Financeiro, Balanços e Certidões'],['editais','Editais e Chamamentos'],['outros','Outros documentos']];
const documentCategoryLabels=Object.fromEntries(documentCategories);

const defs={
  news:{label:'Notícias',table:'news_posts',titleKey:'title',fields:[['title','Título','text',true],['slug','Slug','text'],['excerpt','Resumo','textarea'],['body','Conteúdo','textarea'],['cover_image_url','Imagem de capa','image'],['status','Status','select',['draft','published']],['published_at','Data de publicação','datetime-local']]},
  projects:{label:'Projetos',table:'projects',titleKey:'title',fields:[['title','Título','text',true],['summary','Resumo','textarea'],['body','Descrição completa','textarea'],['image_url','Imagem','image'],['active','Ativo','checkbox'],['display_order','Ordem','number']]},
  events:{label:'Eventos',table:'events',titleKey:'title',fields:[['title','Título','text',true],['description','Descrição','textarea'],['event_date','Data e hora','datetime-local'],['location','Local','text'],['image_url','Imagem','image'],['registration_url','Link de inscrição','url'],['status','Status','select',['draft','published','cancelled']]]},
  athletes:{label:'Atletas',table:'athletes',titleKey:'name',fields:[['name','Nome','text',true],['category','Categoria','text'],['specialty','Prova / Especialidade','text'],['bio','Biografia','textarea'],['photo_url','Foto','image'],['featured','Destaque','checkbox'],['active','Ativo','checkbox'],['display_order','Ordem','number']]},
  team:{label:'Equipe',table:'team_members',titleKey:'name',fields:[['name','Nome','text',true],['role','Função','text'],['bio','Biografia','textarea'],['photo_url','Foto','image'],['active','Ativo','checkbox'],['display_order','Ordem','number']]},
  gallery:{label:'Galeria',table:'gallery_items',titleKey:'caption',fields:[['image_url','Imagem','image',true],['caption','Legenda','text'],['event_name','Evento','text'],['event_date','Data','date'],['active','Ativo','checkbox'],['display_order','Ordem','number']]},
  partners:{label:'Parceiros',table:'partners',titleKey:'name',fields:[['name','Nome','text',true],['partner_type','Tipo','select',['sponsor','supporter','institutional']],['logo_url','Logo','image'],['website_url','Site','url'],['active','Ativo','checkbox'],['display_order','Ordem','number']]},
  documents:{label:'Transparência',table:'documents',titleKey:'title',fields:[['title','Título do documento','text',true],['category','Categoria','select',documentCategories],['file_url','Arquivo PDF / documento','file',true],['document_date','Data de referência do documento','date'],['is_published','Exibir no Portal da Transparência','checkbox'],['display_order','Ordem de exibição','number']]},
};
const defaults={news:{status:'draft'},projects:{active:true,display_order:0},events:{status:'published'},athletes:{active:true,featured:false,display_order:0},team:{active:true,display_order:0},gallery:{active:true,display_order:0},partners:{partner_type:'sponsor',active:true,display_order:0},documents:{category:'outros',is_published:true,display_order:0}};

function notice(){return `${state.err?`<div class="notice err">${esc(state.err)}</div>`:''}${state.msg?`<div class="notice ok">${esc(state.msg)}</div>`:''}`}
function clearNotice(){state.err='';state.msg=''}
function renderLogin(){app.innerHTML=`<div class="login-shell"><div class="login-card"><img class="login-logo" src="assets/logo-sbatletismo.svg" alt="SBAtletismo"><h1>Área administrativa</h1><p>Os responsáveis da associação atualizam o site por aqui.</p>${notice()}<form id="login-form"><label class="field"><span>E-MAIL</span><input class="input" name="email" type="email" value="sbatletismo@gmail.com" required autocomplete="email"></label><label class="field"><span>SENHA</span><input class="input" name="password" type="password" required minlength="6" autocomplete="current-password"></label><div class="login-actions"><button class="btn-admin" type="submit">Entrar</button><button class="btn-admin secondary" id="first-access" type="button">Criar primeiro acesso</button></div></form><div class="notice info">No primeiro acesso, use o e-mail autorizado da associação. Se a confirmação de e-mail estiver ativa, abra a mensagem enviada pelo Supabase e depois volte para entrar.</div><p style="margin-top:18px"><a href="index.html" style="color:#2c3091;font-weight:800">← Voltar ao site</a></p></div></div>`;bindLogin()}
function bindLogin(){document.querySelector('#login-form')?.addEventListener('submit',async e=>{e.preventDefault();clearNotice();const f=new FormData(e.currentTarget);const {error}=await sb.auth.signInWithPassword({email:String(f.get('email')).trim(),password:String(f.get('password'))});if(error){state.err=error.message;renderLogin();return}await enterAdmin()});document.querySelector('#first-access')?.addEventListener('click',async()=>{clearNotice();const form=document.querySelector('#login-form');const f=new FormData(form);const email=String(f.get('email')).trim(),password=String(f.get('password'));if(!email||password.length<6){state.err='Informe o e-mail e uma senha com pelo menos 6 caracteres.';renderLogin();return}const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:new URL('admin.html',location.href).href}});if(error){state.err=error.message;renderLogin();return}if(data.session){await enterAdmin();return}state.msg='Primeiro acesso criado. Confira o e-mail para confirmar a conta e depois entre com a senha escolhida.';renderLogin()})}
async function claimAndCheck(){const {data}=await sb.from('admin_users').select('id').eq('id',state.session.user.id).maybeSingle();return !!data}
async function enterAdmin(){const {data:{session}}=await sb.auth.getSession();state.session=session;if(!session){renderLogin();return}const ok=await claimAndCheck();if(!ok){await sb.auth.signOut();state.session=null;state.err='Este e-mail não está autorizado para administrar o site.';renderLogin();return}state.view='dashboard';state.edit=null;await loadView()}
function navButton(view,label){return `<button data-view="${view}" class="${state.view===view?'active':''}">${label}</button>`}
function shell(content,title='Painel administrativo'){app.innerHTML=`<div class="admin-shell"><aside class="admin-side"><div class="admin-brand"><img src="assets/logo-sbatletismo.svg" alt="SBAtletismo"></div><nav class="admin-nav">${navButton('dashboard','Visão geral')}${navButton('settings','Configurações')}${navButton('news','Notícias')}${navButton('projects','Projetos')}${navButton('events','Eventos')}${navButton('athletes','Atletas')}${navButton('team','Equipe')}${navButton('gallery','Galeria')}${navButton('partners','Parceiros')}${navButton('documents','Transparência')}</nav><div class="admin-side-footer"><small>${esc(state.session?.user?.email||'')}</small><button id="logout" class="btn-admin secondary small">Sair</button><a class="btn-admin secondary small" href="index.html" target="_blank">Abrir site ↗</a></div></aside><main class="admin-main"><header class="admin-top"><div><small>SBATLETISMO</small><h2>${esc(title)}</h2></div><a class="btn-admin secondary small" href="index.html" target="_blank">Ver site ↗</a></header><div class="admin-content">${notice()}${content}</div></main></div>`;bindShell()}
function bindShell(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',async()=>{clearNotice();state.view=b.dataset.view;state.edit=null;await loadView()}));document.querySelector('#logout')?.addEventListener('click',async()=>{await sb.auth.signOut();state.session=null;renderLogin()})}
async function loadCounts(){const keys=Object.entries(defs);const res=await Promise.all(keys.map(([,d])=>sb.from(d.table).select('*',{count:'exact',head:true})));state.counts=Object.fromEntries(keys.map(([k],i)=>[k,res[i].count||0]))}
async function renderDashboard(){await loadCounts();shell(`<section class="admin-hero"><small>CONTEÚDO DO SITE</small><h1>Bem-vindo ao painel da SBAtletismo.</h1><p>Publique e atualize o site sem precisar editar código. As alterações salvas aqui ficam disponíveis no site público conforme o status de publicação.</p></section><div class="quick-grid"><div class="quick-card"><strong>${state.counts.news||0}</strong><span>Notícias</span></div><div class="quick-card"><strong>${state.counts.projects||0}</strong><span>Projetos</span></div><div class="quick-card"><strong>${state.counts.athletes||0}</strong><span>Atletas</span></div><div class="quick-card"><strong>${state.counts.documents||0}</strong><span>Documentos públicos</span></div></div><section class="panel"><div class="panel-head"><div><h3>Atalhos</h3><p>Comece pelas áreas mais usadas.</p></div></div><div class="quick-grid"><button class="quick-card" data-jump="news" style="text-align:left;border:1px solid #e3e8f0"><strong>＋</strong><span>Publicar notícia</span></button><button class="quick-card" data-jump="gallery" style="text-align:left;border:1px solid #e3e8f0"><strong>＋</strong><span>Adicionar foto</span></button><button class="quick-card" data-jump="documents" style="text-align:left;border:1px solid #e3e8f0"><strong>＋</strong><span>Enviar documento público</span></button><button class="quick-card" data-jump="settings" style="text-align:left;border:1px solid #e3e8f0"><strong>⚙</strong><span>Dados do site</span></button></div></section>`,'Visão geral');document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',async()=>{state.view=b.dataset.jump;state.edit=null;await loadView()}))}
async function renderSettings(){const {data,error}=await sb.from('site_settings').select('*').eq('id',1).single();if(error){state.err=error.message;shell('','Configurações');return}state.settings=data;const f=data||{};shell(`<section class="panel"><div class="panel-head"><div><h3>Dados gerais do site</h3><p>Textos e contatos principais.</p></div></div><form id="settings-form"><div class="form-grid">${input('organization_name','Nome da associação',f.organization_name)}${input('tagline','Slogan',f.tagline)}${input('hero_title','Título principal',f.hero_title)}${input('hero_subtitle','Texto principal',f.hero_subtitle,'textarea','full')}${input('about_text','Sobre a associação',f.about_text,'textarea','full')}${input('logo_url','Logo da associação (URL)',f.logo_url,'url')}${filePicker('logo_upload','Enviar novo logo')}${input('hero_image_url','Imagem principal (URL)',f.hero_image_url,'url')}${filePicker('hero_upload','Enviar nova imagem principal')}${input('contact_email','E-mail',f.contact_email,'email')}${input('contact_phone','Telefone / WhatsApp',f.contact_phone)}${input('address','Endereço',f.address,'textarea','full')}${input('instagram_url','Instagram',f.instagram_url,'url')}${input('facebook_url','Facebook',f.facebook_url,'url')}${input('youtube_url','YouTube',f.youtube_url,'url')}${input('registration_url','Link de inscrição',f.registration_url,'url')}</div><div class="form-actions"><button class="btn-admin" type="submit">Salvar alterações</button></div></form></section>`,'Configurações');document.querySelector('#settings-form').addEventListener('submit',saveSettings)}
function input(name,label,value='',type='text',extra=''){if(type==='textarea')return `<label class="field ${extra}"><span>${esc(label)}</span><textarea class="textarea" name="${name}">${esc(value||'')}</textarea></label>`;return `<label class="field ${extra}"><span>${esc(label)}</span><input class="input" name="${name}" type="${type}" value="${esc(value||'')}"></label>`}
function filePicker(name,label,accept='image/*'){return `<label class="field"><span>${esc(label)}</span><div class="upload-box"><input name="${name}" type="file" accept="${accept}"><small>O arquivo será enviado para o armazenamento da SBAtletismo.</small></div></label>`}
async function upload(file,bucket,folder){if(!file||!file.size)return'';const safe=file.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${folder}/${Date.now()}-${crypto.randomUUID()}-${safe}`;const {error}=await sb.storage.from(bucket).upload(path,file,{contentType:file.type||undefined,upsert:false});if(error)throw error;return sb.storage.from(bucket).getPublicUrl(path).data.publicUrl}
async function saveSettings(e){e.preventDefault();clearNotice();try{const fd=new FormData(e.currentTarget),payload={};['organization_name','tagline','hero_title','hero_subtitle','about_text','logo_url','hero_image_url','contact_email','contact_phone','address','instagram_url','facebook_url','youtube_url','registration_url'].forEach(k=>payload[k]=String(fd.get(k)||'').trim()||null);const logoFile=fd.get('logo_upload');if(logoFile?.size)payload.logo_url=await upload(logoFile,'site-media','branding');const file=fd.get('hero_upload');if(file?.size)payload.hero_image_url=await upload(file,'site-media','settings');const {error}=await sb.from('site_settings').update(payload).eq('id',1);if(error)throw error;state.msg='Configurações salvas.';await renderSettings()}catch(err){state.err=err.message||String(err);await renderSettings()}}
function fieldHtml(field,row){const [name,label,type,opts]=field;const val=row?.[name]??defaults[state.view]?.[name]??'';const req=opts===true?'required':'';if(type==='textarea')return `<label class="field full"><span>${esc(label)}</span><textarea class="textarea" name="${name}" ${req}>${esc(val)}</textarea></label>`;if(type==='select'){return `<label class="field"><span>${esc(label)}</span><select class="select" name="${name}">${opts.map(o=>{const pair=Array.isArray(o)?o:[o,o];const value=String(pair[0]),text=String(pair[1]);return `<option value="${esc(value)}" ${String(val)===value?'selected':''}>${esc(text)}</option>`}).join('')}</select></label>`}if(type==='checkbox')return `<label class="field"><span>${esc(label)}</span><label style="display:flex;align-items:center;gap:8px;padding:11px 0"><input name="${name}" type="checkbox" ${val?'checked':''}> Sim</label></label>`;if(type==='image')return `<label class="field"><span>${esc(label)}</span><div class="upload-box">${val?`<img src="${esc(val)}" alt="" class="thumb" style="margin-bottom:8px">`:''}<input name="${name}" type="file" accept="image/*"><small>JPG, PNG ou WebP. ${val?'A imagem atual será mantida se você não selecionar outra.':''}</small></div></label>`;if(type==='file')return `<label class="field"><span>${esc(label)}</span><div class="upload-box">${val?`<a href="${esc(val)}" target="_blank" style="color:#2c3091;font-weight:800">Arquivo atual ↗</a>`:''}<input name="${name}" type="file" accept="application/pdf,.pdf,.doc,.docx,.xls,.xlsx" ${!val&&opts===true?'required':''}><small>PDF recomendado para transparência.</small></div></label>`;let display=val;if(type==='datetime-local'&&val)display=String(val).slice(0,16);return `<label class="field"><span>${esc(label)}</span><input class="input" name="${name}" type="${type}" value="${esc(display)}" ${req}></label>`}
function rowMeta(view,r){if(view==='news')return `${r.status} • ${fmt(r.published_at||r.created_at)}`;if(view==='events')return `${r.status} • ${fmt(r.event_date)}`;if(view==='documents')return `${documentCategoryLabels[r.category]||r.category||'Sem categoria'} • ${fmt(r.document_date)} • ${r.is_published?'visível no portal':'oculto do público'}`;if(view==='athletes')return `${r.category||''} ${r.specialty?'• '+r.specialty:''}`;if(view==='team')return r.role||'';if(view==='partners')return r.partner_type||'';if(view==='gallery')return `${r.event_name||''} ${r.event_date?'• '+fmt(r.event_date):''}`;return r.active===false?'inativo':'ativo'}
function rowThumb(view,r){const k={news:'cover_image_url',projects:'image_url',events:'image_url',athletes:'photo_url',team:'photo_url',gallery:'image_url',partners:'logo_url'}[view];return k&&r[k]?`<img class="thumb" src="${esc(r[k])}" alt="">`:''}
async function renderCrud(view){const d=defs[view];let query=sb.from(d.table).select('*');if(view==='documents')query=query.order('display_order',{ascending:true}).order('document_date',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false});else query=query.order('created_at',{ascending:false});const {data,error}=await query;if(error){state.err=error.message;state.rows=[]}else state.rows=data||[];const edit=state.edit?state.rows.find(r=>String(r.id)===String(state.edit)):null;const formRow=edit||defaults[view]||{};const help=view==='documents'?`<div class="notice info"><strong>Portal da Transparência pronto para os administradores.</strong><br>Informe o título, escolha a categoria, envie o arquivo, defina a data de referência e marque a opção de exibição pública. Itens desmarcados ficam salvos no painel, mas não aparecem no portal.</div>`:'';const subtitle=view==='documents'?'Os arquivos publicados aparecem automaticamente no Portal da Transparência.':'Salve para atualizar o banco da associação.';shell(`${help}<section class="panel"><div class="panel-head"><div><h3>${edit?'Editar':'Adicionar'} ${esc(d.label.toLowerCase())}</h3><p>${subtitle}</p></div>${edit?'<button id="cancel-edit" class="btn-admin secondary small">Cancelar edição</button>':''}</div><form id="crud-form"><div class="form-grid">${d.fields.map(f=>fieldHtml(f,formRow)).join('')}</div><div class="form-actions"><button class="btn-admin" type="submit">${edit?'Salvar alterações':'Adicionar'}</button></div></form></section><section class="panel"><div class="panel-head"><div><h3>${view==='documents'?'Documentos cadastrados':esc(d.label)+' cadastrados'}</h3><p>${state.rows.length} item(ns).</p></div></div><div class="admin-list">${state.rows.length?state.rows.map(r=>`<div class="admin-row"><div class="row-with-thumb">${rowThumb(view,r)}<div><h4>${esc(r[d.titleKey]||r.name||r.title||'Sem título')}</h4><p>${esc(rowMeta(view,r))}</p></div></div><div class="row-actions"><button class="btn-admin secondary small" data-edit="${r.id}">Editar</button><button class="btn-admin danger small" data-delete="${r.id}">Excluir</button></div></div>`).join(''):'<div class="empty">Nenhum item cadastrado ainda.</div>'}</div></section>`,d.label);bindCrud(view,d)}
function bindCrud(view,d){document.querySelector('#crud-form')?.addEventListener('submit',e=>saveCrud(e,view,d));document.querySelector('#cancel-edit')?.addEventListener('click',async()=>{state.edit=null;await renderCrud(view)});document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',async()=>{state.edit=b.dataset.edit;await renderCrud(view);window.scrollTo({top:0,behavior:'smooth'})}));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Excluir este item?'))return;clearNotice();const {error}=await sb.from(d.table).delete().eq('id',b.dataset.delete);if(error)state.err=error.message;else state.msg='Item excluído.';state.edit=null;await renderCrud(view)}))}
async function saveCrud(e,view,d){e.preventDefault();clearNotice();try{const fd=new FormData(e.currentTarget),current=state.edit?state.rows.find(r=>String(r.id)===String(state.edit))||{}:{},payload={};for(const f of d.fields){const [name,,type]=f;if(type==='image'){const file=fd.get(name);payload[name]=file?.size?await upload(file,'site-media',d.table):(current[name]||null)}else if(type==='file'){const file=fd.get(name);payload[name]=file?.size?await upload(file,'documents',d.table):(current[name]||null)}else if(type==='checkbox'){payload[name]=fd.get(name)==='on'}else if(type==='number'){payload[name]=Number(fd.get(name)||0)}else{const raw=String(fd.get(name)||'').trim();payload[name]=raw||null}}
    if(view==='news'){if(!payload.slug)payload.slug=slugify(payload.title);if(payload.status==='published'&&!payload.published_at)payload.published_at=new Date().toISOString()}
    if(state.edit){const {error}=await sb.from(d.table).update(payload).eq('id',state.edit);if(error)throw error;state.msg='Alterações salvas.'}else{const {error}=await sb.from(d.table).insert(payload);if(error)throw error;state.msg='Item adicionado.'}state.edit=null;await renderCrud(view)}catch(err){state.err=err.message||String(err);await renderCrud(view)}}
async function loadView(){if(!state.session){renderLogin();return}if(state.view==='dashboard')return renderDashboard();if(state.view==='settings')return renderSettings();if(defs[state.view])return renderCrud(state.view)}

sb.auth.onAuthStateChange(async(_event,session)=>{state.session=session;if(session&&!app.querySelector('.admin-shell'))await enterAdmin();if(!session&&!app.querySelector('.login-shell'))renderLogin()});
(async()=>{const {data:{session}}=await sb.auth.getSession();state.session=session;if(session)await enterAdmin();else renderLogin()})();
