import { supabase } from './config.js';
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v?new Intl.DateTimeFormat('pt-BR').format(new Date(v+'T12:00:00')):'—';
const goodUrl=v=>{try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
const labels={institucional:'Institucional',emendas:'Emendas e termos',planos:'Planos de trabalho',contas:'Prestação de contas',relatorios:'Relatórios',balancos:'Balanços e certidões',outros:'Outros'};
let docs=[],category='all';
const q=document.querySelector('#search-doc'),year=document.querySelector('#portal-year'),kind=document.querySelector('#portal-kind'),body=document.querySelector('#document-body'),empty=document.querySelector('#empty-state');
document.querySelector('#portal-footer-year').textContent=new Date().getFullYear();
function counts(){document.querySelectorAll('.category-button').forEach(b=>{const c=b.dataset.category;const n=c==='all'?docs.length:docs.filter(d=>d.category===c).length;b.querySelector('b').textContent=n})}
function render(){const term=q.value.trim().toLowerCase(),yr=year.value,k=kind.value;let out=docs.filter(d=>(category==='all'||d.category===category)&&(k==='all'||d.category===k)&&(yr==='all'||String(d.document_date||'').startsWith(yr))&&(!term||`${d.title} ${d.category}`.toLowerCase().includes(term)));body.innerHTML=out.map(d=>`<tr><td><strong>${esc(d.title)}</strong></td><td>${esc(labels[d.category]||d.category)}</td><td>${esc(fmt(d.document_date))}</td><td><a class="file-link" href="${esc(goodUrl(d.file_url))}" target="_blank" rel="noopener">Abrir ↗</a></td></tr>`).join('');empty.classList.toggle('hidden',out.length>0);document.querySelector('#result-title').textContent=yr==='all'?'Documentos publicados':`Documentos de ${yr}`;document.querySelector('#result-subtitle').textContent=`${out.length} documento(s) encontrado(s).`}
async function load(){const {data,error}=await supabase.from('documents').select('*').order('document_date',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false});if(error){empty.textContent='Não foi possível carregar os documentos.';empty.classList.remove('hidden');return}docs=data||[];const years=[...new Set(docs.map(d=>String(d.document_date||'').slice(0,4)).filter(Boolean))].sort((a,b)=>b.localeCompare(a));year.insertAdjacentHTML('beforeend',years.map(y=>`<option value="${esc(y)}">${esc(y)}</option>`).join(''));counts();render()}
[q,year,kind].forEach(el=>el.addEventListener(el===q?'input':'change',render));document.querySelectorAll('.category-button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.category-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');category=b.dataset.category;kind.value='all';render()}));load();
